# https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github?hl=ja#add_configuration_files
have_fun: true
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false
    code_review: false
